### ISSUE TITLE
memory need

### ISSUE THREAD

**Issue by saeedehghanadbashi** [asjad99/MIMIC_RL_COACH#2]
Hi, I've completed the steps until this command 'make build_curated_from_psql', however in running this command I got the error message 137 which indicates that the memory limitation. I've used the Google cloud with 32 Gig ram. Would you please let me know is that the problem related to memory or not? Thanks.

**Comment by asjad99** [comment]
Hi would recommend atleast 50GB ram for pre-processing steps
